import type { StationVisualAsset } from "@/lib/station-visual/types";

const stationVisualRoot = "/images/recipe-library/station-visuals";
const stationCoverRoot = "/images/recipe-library/station-covers";

export const stationVisualManifest: StationVisualAsset[] = [
  {
    id: "station-chicken-kung-pao-01",
    src: `${stationCoverRoot}/kung-pao-chicken-cover.png`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["宫保鸡丁", "Kung Pao Chicken"],
    aliases: ["宫爆鸡丁", "Kung Bao Chicken"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["diced"],
    keyIngredients: ["chicken", "dried-chili", "peanut", "peppercorn", "scallion"],
    flavorTags: ["spicy", "sweet-sour"],
    composition: "radial",
    objectPosition: "50% 56%",
  },
  {
    id: "station-chicken-kung-pao-02",
    src: `${stationCoverRoot}/kung-pao-chicken-cover-alt.png`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["宫保鸡丁", "Kung Pao Chicken"],
    aliases: ["宫爆鸡丁", "Kung Bao Chicken"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["diced"],
    keyIngredients: ["chicken", "dried-chili", "peanut", "peppercorn", "scallion"],
    flavorTags: ["spicy", "sweet-sour"],
    composition: "elliptical",
    objectPosition: "48% 55%",
  },
  {
    id: "station-chicken-yellow-braised-01",
    src: `${stationCoverRoot}/huang-men-chicken-cover.png`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["黄焖鸡", "Braised Chicken"],
    aliases: ["黄焖鸡米饭"],
    cookingMethods: ["braise", "stew"],
    ingredientForms: ["chunks"],
    keyIngredients: ["chicken", "mushroom", "green-pepper", "ginger", "garlic"],
    flavorTags: ["savory"],
    composition: "balanced",
    objectPosition: "50% 55%",
  },
  {
    id: "station-chicken-spicy-01",
    src: `${stationCoverRoot}/spicy-chicken-cover.png`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["辣子鸡", "Spicy Chicken"],
    aliases: ["重庆辣子鸡"],
    cookingMethods: ["stir-fry", "fry"],
    ingredientForms: ["chunks", "diced"],
    keyIngredients: ["chicken", "dried-chili", "peppercorn", "sesame", "scallion"],
    flavorTags: ["spicy"],
    composition: "half-circle",
    objectPosition: "51% 55%",
  },
  {
    id: "station-chicken-cola-wings-01",
    src: `${stationVisualRoot}/chicken/station-chicken-cola-wings-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["可乐鸡翅", "Cola Chicken Wings"],
    aliases: ["可乐翅中"],
    cookingMethods: ["braise"],
    ingredientForms: ["wings"],
    keyIngredients: ["chicken", "ginger", "scallion", "star-anise", "soy-sauce"],
    flavorTags: ["sweet", "savory"],
    composition: "diagonal",
    objectPosition: "50% 56%",
  },
  {
    id: "station-chicken-potato-01",
    src: `${stationVisualRoot}/chicken/station-chicken-potato-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["土豆烧鸡", "Potato Chicken"],
    aliases: ["土豆炖鸡", "黄焖鸡腿"],
    cookingMethods: ["braise", "stew"],
    ingredientForms: ["chunks"],
    keyIngredients: ["chicken", "potato", "carrot", "star-anise", "scallion"],
    flavorTags: ["savory"],
    composition: "elliptical",
    objectPosition: "50% 56%",
  },
  {
    id: "station-chicken-mushroom-01",
    src: `${stationVisualRoot}/chicken/station-chicken-mushroom-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["香菇滑鸡", "Mushroom Chicken"],
    aliases: ["香菇蒸滑鸡"],
    cookingMethods: ["steam", "stir-fry"],
    ingredientForms: ["sliced", "chunks"],
    keyIngredients: ["chicken", "mushroom", "scallion", "ginger", "red-pepper"],
    flavorTags: ["savory"],
    composition: "flow",
    objectPosition: "49% 55%",
  },
  {
    id: "station-chicken-green-pepper-01",
    src: `${stationVisualRoot}/chicken/station-chicken-green-pepper-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["青椒炒鸡丁", "Green Pepper Chicken"],
    aliases: ["双椒鸡丁"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["diced"],
    keyIngredients: ["chicken", "green-pepper", "red-pepper", "garlic", "scallion"],
    flavorTags: ["savory"],
    composition: "balanced",
    objectPosition: "51% 55%",
  },
  {
    id: "station-chicken-peppercorn-01",
    src: `${stationVisualRoot}/chicken/station-chicken-peppercorn-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["花椒鸡", "Peppercorn Chicken"],
    aliases: ["青花椒鸡"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["chunks"],
    keyIngredients: ["chicken", "peppercorn", "red-chili", "scallion", "ginger"],
    flavorTags: ["spicy", "numbing"],
    composition: "half-circle",
    objectPosition: "50% 54%",
  },
  {
    id: "station-chicken-ginger-scallion-01",
    src: `${stationVisualRoot}/chicken/station-chicken-ginger-scallion-01.webp`,
    type: "station-visual",
    primaryCategory: "chicken",
    compatibleCategories: ["chicken"],
    dishNames: ["姜葱鸡", "Ginger Scallion Chicken"],
    aliases: ["葱油鸡"],
    cookingMethods: ["steam", "poach"],
    ingredientForms: ["chunks"],
    keyIngredients: ["chicken", "scallion", "ginger", "cilantro"],
    flavorTags: ["fresh", "savory"],
    composition: "flow",
    objectPosition: "49% 55%",
    isCategoryFallback: true,
  },
  {
    id: "station-beef-stew-01",
    src: `${stationVisualRoot}/beef/station-beef-stew-01.webp`,
    type: "station-visual",
    primaryCategory: "beef",
    compatibleCategories: ["beef"],
    dishNames: ["土豆炖牛肉", "Beef Stew"],
    aliases: ["土豆烧牛肉"],
    cookingMethods: ["stew", "braise"],
    ingredientForms: ["chunks"],
    keyIngredients: ["beef", "potato", "carrot", "onion", "star-anise"],
    flavorTags: ["savory"],
    composition: "elliptical",
    objectPosition: "50% 56%",
  },
  {
    id: "station-beef-black-pepper-01",
    src: `${stationVisualRoot}/beef/station-beef-black-pepper-01.webp`,
    type: "station-visual",
    primaryCategory: "beef",
    compatibleCategories: ["beef"],
    dishNames: ["黑椒牛柳", "Black Pepper Beef"],
    aliases: ["黑椒牛肉"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["strips"],
    keyIngredients: ["beef", "black-pepper", "green-pepper", "onion"],
    flavorTags: ["peppery", "savory"],
    composition: "diagonal",
    objectPosition: "51% 55%",
  },
  {
    id: "station-beef-tomato-brisket-01",
    src: `${stationVisualRoot}/beef/station-beef-tomato-brisket-01.webp`,
    type: "station-visual",
    primaryCategory: "beef",
    compatibleCategories: ["beef"],
    dishNames: ["番茄牛腩", "Tomato Beef Brisket"],
    aliases: ["西红柿炖牛腩"],
    cookingMethods: ["stew"],
    ingredientForms: ["chunks"],
    keyIngredients: ["beef", "tomato", "potato", "onion"],
    flavorTags: ["sweet-sour", "savory"],
    composition: "balanced",
    objectPosition: "49% 56%",
  },
  {
    id: "station-beef-generic-01",
    src: `${stationVisualRoot}/beef/station-beef-generic-01.webp`,
    type: "station-visual",
    primaryCategory: "beef",
    compatibleCategories: ["beef"],
    dishNames: [],
    aliases: [],
    cookingMethods: ["stir-fry", "stew", "braise"],
    ingredientForms: ["chunks", "sliced", "strips"],
    keyIngredients: ["beef", "scallion", "ginger", "garlic"],
    flavorTags: ["savory"],
    composition: "radial",
    objectPosition: "50% 55%",
    isCategoryFallback: true,
  },
  {
    id: "station-pork-red-braised-01",
    src: `${stationVisualRoot}/pork/station-pork-red-braised-01.webp`,
    type: "station-visual",
    primaryCategory: "pork",
    compatibleCategories: ["pork"],
    dishNames: ["红烧肉", "Red Braised Pork"],
    aliases: ["红烧五花肉"],
    cookingMethods: ["braise"],
    ingredientForms: ["chunks"],
    keyIngredients: ["pork", "star-anise", "ginger", "scallion", "rock-sugar"],
    flavorTags: ["sweet", "savory"],
    composition: "radial",
    objectPosition: "50% 56%",
  },
  {
    id: "station-pork-ribs-01",
    src: `${stationVisualRoot}/pork/station-pork-ribs-01.webp`,
    type: "station-visual",
    primaryCategory: "pork",
    compatibleCategories: ["pork"],
    dishNames: ["糖醋排骨", "Sweet Sour Ribs"],
    aliases: ["糖醋小排"],
    cookingMethods: ["fry", "braise"],
    ingredientForms: ["ribs"],
    keyIngredients: ["pork", "ginger", "scallion", "vinegar", "sugar"],
    flavorTags: ["sweet-sour"],
    composition: "diagonal",
    objectPosition: "49% 55%",
  },
  {
    id: "station-pork-generic-01",
    src: `${stationVisualRoot}/pork/station-pork-generic-01.webp`,
    type: "station-visual",
    primaryCategory: "pork",
    compatibleCategories: ["pork"],
    dishNames: ["鱼香肉丝", "Fish Fragrant Pork"],
    aliases: ["鱼香肉丝家常版"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["strips", "sliced"],
    keyIngredients: ["pork", "bamboo-shoot", "fungus", "red-pepper"],
    flavorTags: ["spicy", "sweet-sour"],
    composition: "flow",
    objectPosition: "51% 55%",
    isCategoryFallback: true,
  },
  {
    id: "station-fish-steamed-01",
    src: `${stationVisualRoot}/fish/station-fish-steamed-01.webp`,
    type: "station-visual",
    primaryCategory: "fish",
    compatibleCategories: ["fish"],
    dishNames: ["清蒸鱼", "Steamed Fish"],
    aliases: ["清蒸鲈鱼"],
    cookingMethods: ["steam"],
    ingredientForms: ["whole"],
    keyIngredients: ["fish", "scallion", "ginger", "red-pepper", "soy-sauce"],
    flavorTags: ["fresh", "savory"],
    composition: "diagonal",
    objectPosition: "50% 55%",
  },
  {
    id: "station-fish-boiled-01",
    src: `${stationVisualRoot}/fish/station-fish-boiled-01.webp`,
    type: "station-visual",
    primaryCategory: "fish",
    compatibleCategories: ["fish"],
    dishNames: ["水煮鱼", "Boiled Fish"],
    aliases: ["水煮鱼片"],
    cookingMethods: ["boil"],
    ingredientForms: ["fillets", "sliced"],
    keyIngredients: ["fish", "dried-chili", "peppercorn", "bean-sprout"],
    flavorTags: ["spicy", "numbing"],
    composition: "half-circle",
    objectPosition: "50% 55%",
  },
  {
    id: "station-fish-pan-fried-01",
    src: `${stationVisualRoot}/fish/station-fish-pan-fried-01.webp`,
    type: "station-visual",
    primaryCategory: "fish",
    compatibleCategories: ["fish"],
    dishNames: ["香煎带鱼", "Pan-fried Ribbonfish"],
    aliases: ["干煎带鱼"],
    cookingMethods: ["fry"],
    ingredientForms: ["sliced"],
    keyIngredients: ["fish", "ginger", "scallion", "peppercorn"],
    flavorTags: ["savory"],
    composition: "flow",
    objectPosition: "50% 55%",
    isCategoryFallback: true,
  },
  {
    id: "station-seafood-garlic-shrimp-01",
    src: `${stationVisualRoot}/seafood/station-seafood-garlic-shrimp-01.webp`,
    type: "station-visual",
    primaryCategory: "seafood",
    compatibleCategories: ["shrimp"],
    dishNames: ["蒜蓉粉丝虾", "Garlic Vermicelli Shrimp"],
    aliases: ["蒜蓉开背虾"],
    cookingMethods: ["steam"],
    ingredientForms: ["whole"],
    keyIngredients: ["shrimp", "garlic", "vermicelli", "scallion"],
    flavorTags: ["garlicky", "savory"],
    composition: "half-circle",
    objectPosition: "50% 55%",
  },
  {
    id: "station-seafood-spicy-squid-01",
    src: `${stationVisualRoot}/seafood/station-seafood-spicy-squid-01.webp`,
    type: "station-visual",
    primaryCategory: "seafood",
    compatibleCategories: ["shrimp", "crab"],
    dishNames: ["香辣鱿鱼", "Spicy Squid"],
    aliases: ["香辣海鲜"],
    cookingMethods: ["stir-fry"],
    ingredientForms: ["sliced"],
    keyIngredients: ["seafood", "red-chili", "green-pepper", "garlic"],
    flavorTags: ["spicy"],
    composition: "flow",
    objectPosition: "51% 55%",
  },
  {
    id: "station-seafood-generic-01",
    src: `${stationVisualRoot}/seafood/station-seafood-generic-01.webp`,
    type: "station-visual",
    primaryCategory: "seafood",
    compatibleCategories: ["shrimp", "crab"],
    dishNames: ["清蒸螃蟹", "Steamed Crab"],
    aliases: ["清蒸海鲜"],
    cookingMethods: ["steam"],
    ingredientForms: ["whole"],
    keyIngredients: ["seafood", "crab", "shrimp", "ginger", "scallion"],
    flavorTags: ["fresh"],
    composition: "balanced",
    objectPosition: "50% 55%",
    isCategoryFallback: true,
  },
  {
    id: "station-duck-ginger-01",
    src: `${stationVisualRoot}/duck/station-duck-ginger-01.webp`,
    type: "station-visual",
    primaryCategory: "duck",
    compatibleCategories: ["duck"],
    dishNames: ["姜母鸭", "Ginger Duck"],
    aliases: ["啤酒鸭", "Beer Duck"],
    cookingMethods: ["braise", "stew"],
    ingredientForms: ["chunks"],
    keyIngredients: ["duck", "ginger", "scallion", "star-anise"],
    flavorTags: ["savory"],
    composition: "elliptical",
    objectPosition: "50% 56%",
    isCategoryFallback: true,
  },
];
