import type { HeroVisualAsset } from "@/types/recipeVisual";

export const heroAssetManifest: HeroVisualAsset[] = [
  {
    id: "hero-kung-pao-chicken-01",
    src: "/images/recipe-library/hero/kung-pao-chicken.png",
    dishNames: ["宫保鸡丁", "Kung Pao Chicken"],
    aliases: ["宫爆鸡丁"],
    primaryCategory: "chicken",
    ingredientForms: ["diced", "small-pieces"],
    cookingMethods: ["stir-fry"],
    keyIngredients: ["chicken", "dried-chili", "peanut", "peppercorn"],
    flavorTags: ["sweet-sour", "spicy", "savory"],
    dishForm: "dry-stir-fry",
    objectPosition: "70% 50%",
  },
  {
    id: "hero-yellow-braised-chicken-01",
    src: "/images/recipe-library/hero/yellow-braised-chicken.webp",
    dishNames: ["黄焖鸡", "Yellow Braised Chicken"],
    aliases: ["黄焖鸡米饭"],
    primaryCategory: "chicken",
    ingredientForms: ["chunks", "small-pieces"],
    cookingMethods: ["braise", "stew"],
    keyIngredients: ["chicken", "mushroom", "ginger"],
    flavorTags: ["savory", "rich"],
    dishForm: "braised",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-laziji-chicken-01",
    src: "/images/recipe-library/hero/laziji-chicken.webp",
    dishNames: ["辣子鸡", "Laziji Chicken", "Chongqing Spicy Chicken"],
    aliases: ["重庆辣子鸡", "辣子鸡丁"],
    primaryCategory: "chicken",
    ingredientForms: ["diced", "small-pieces"],
    cookingMethods: ["deep-fry", "stir-fry"],
    keyIngredients: ["chicken", "dried-chili", "peppercorn"],
    flavorTags: ["spicy", "numbing-spicy", "savory"],
    dishForm: "dry-stir-fry",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-beer-duck-01",
    src: "/images/recipe-library/hero/beer-duck.webp",
    dishNames: ["啤酒鸭", "Beer Duck"],
    aliases: [],
    primaryCategory: "duck",
    ingredientForms: ["chunks", "small-pieces"],
    cookingMethods: ["braise", "stew"],
    keyIngredients: ["duck", "beer", "ginger"],
    flavorTags: ["savory", "rich"],
    dishForm: "braised",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-ginger-duck-01",
    src: "/images/recipe-library/hero/ginger-duck.webp",
    dishNames: ["姜母鸭", "Ginger Duck"],
    aliases: ["姜母炖鸭"],
    primaryCategory: "duck",
    ingredientForms: ["chunks", "small-pieces"],
    cookingMethods: ["stew", "braise"],
    keyIngredients: ["duck", "ginger", "sesame-oil"],
    flavorTags: ["savory", "rich"],
    dishForm: "stew",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-red-braised-pork-01",
    src: "/images/recipe-library/hero/red-braised-pork.webp",
    dishNames: ["红烧肉", "Red Braised Pork"],
    aliases: ["红烧五花肉"],
    primaryCategory: "pork",
    ingredientForms: ["chunks", "small-pieces"],
    cookingMethods: ["braise"],
    keyIngredients: ["pork", "soy-sauce", "sugar"],
    flavorTags: ["sweet-savory", "savory", "rich"],
    dishForm: "braised",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-fish-fragrant-pork-01",
    src: "/images/recipe-library/hero/fish-fragrant-pork.webp",
    dishNames: ["鱼香肉丝", "Fish Fragrant Pork"],
    aliases: ["鱼香猪肉丝", "Yuxiang Shredded Pork"],
    primaryCategory: "pork",
    ingredientForms: ["shredded"],
    cookingMethods: ["stir-fry"],
    keyIngredients: ["pork", "wood-ear", "bamboo-shoot", "chili"],
    flavorTags: ["sweet-sour", "spicy", "savory"],
    dishForm: "dry-stir-fry",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-sweet-sour-ribs-01",
    src: "/images/recipe-library/hero/sweet-sour-ribs.webp",
    dishNames: ["糖醋排骨", "Sweet and Sour Ribs"],
    aliases: ["糖醋小排"],
    primaryCategory: "pork",
    ingredientForms: ["chunks", "ribs"],
    cookingMethods: ["deep-fry", "braise"],
    keyIngredients: ["pork", "vinegar", "sugar"],
    flavorTags: ["sweet-sour", "rich"],
    dishForm: "braised",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-beef-stew-01",
    src: "/images/recipe-library/hero/beef-stew.webp",
    dishNames: ["土豆炖牛肉", "Beef Stew with Potato"],
    aliases: ["土豆烧牛肉"],
    primaryCategory: "beef",
    ingredientForms: ["chunks"],
    cookingMethods: ["stew"],
    keyIngredients: ["beef", "potato", "carrot"],
    flavorTags: ["savory", "rich"],
    dishForm: "stew",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-black-pepper-beef-01",
    src: "/images/recipe-library/hero/black-pepper-beef.webp",
    dishNames: ["黑椒牛柳", "Black Pepper Beef"],
    aliases: ["黑胡椒牛柳"],
    primaryCategory: "beef",
    ingredientForms: ["sliced", "strips"],
    cookingMethods: ["stir-fry"],
    keyIngredients: ["beef", "black-pepper", "onion", "bell-pepper"],
    flavorTags: ["savory", "peppery"],
    dishForm: "dry-stir-fry",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-tomato-beef-brisket-01",
    src: "/images/recipe-library/hero/tomato-beef-brisket.webp",
    dishNames: ["番茄牛腩", "Tomato Beef Brisket"],
    aliases: ["西红柿炖牛腩", "番茄炖牛腩"],
    primaryCategory: "beef",
    ingredientForms: ["chunks"],
    cookingMethods: ["stew"],
    keyIngredients: ["beef", "tomato"],
    flavorTags: ["sweet-sour", "savory", "rich"],
    dishForm: "stew",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-steamed-fish-01",
    src: "/images/recipe-library/hero/steamed-fish.webp",
    dishNames: ["清蒸鱼", "Steamed Fish"],
    aliases: ["清蒸鲈鱼", "清蒸整鱼"],
    primaryCategory: "fish",
    ingredientForms: ["whole"],
    cookingMethods: ["steam"],
    keyIngredients: ["fish", "scallion", "ginger"],
    flavorTags: ["light", "savory"],
    dishForm: "whole-fish",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-boiled-fish-01",
    src: "/images/recipe-library/hero/boiled-fish.webp",
    dishNames: ["水煮鱼", "Sichuan Boiled Fish"],
    aliases: ["水煮鱼片"],
    primaryCategory: "fish",
    ingredientForms: ["sliced", "fillet"],
    cookingMethods: ["boil"],
    keyIngredients: ["fish", "dried-chili", "peppercorn"],
    flavorTags: ["spicy", "numbing-spicy", "savory"],
    dishForm: "soup",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-pan-fried-fish-01",
    src: "/images/recipe-library/hero/pan-fried-fish.webp",
    dishNames: ["香煎鱼", "Pan Fried Fish"],
    aliases: ["煎鱼", "香煎整鱼"],
    primaryCategory: "fish",
    ingredientForms: ["whole", "fillet"],
    cookingMethods: ["pan-fry"],
    keyIngredients: ["fish", "ginger", "scallion"],
    flavorTags: ["savory"],
    dishForm: "fried",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-garlic-vermicelli-shrimp-01",
    src: "/images/recipe-library/hero/garlic-vermicelli-shrimp.webp",
    dishNames: ["蒜蓉粉丝虾", "Garlic Vermicelli Shrimp"],
    aliases: ["蒜蓉蒸虾", "粉丝蒸虾"],
    primaryCategory: "shrimp",
    ingredientForms: ["whole", "shellfish"],
    cookingMethods: ["steam"],
    keyIngredients: ["shrimp", "garlic", "vermicelli"],
    flavorTags: ["garlic", "savory"],
    dishForm: "steamed-seafood",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-spicy-squid-01",
    src: "/images/recipe-library/hero/spicy-squid.webp",
    dishNames: ["辣炒鱿鱼", "Spicy Stir Fried Squid"],
    aliases: ["香辣鱿鱼", "爆炒鱿鱼"],
    primaryCategory: "shrimp",
    ingredientForms: ["sliced", "rings"],
    cookingMethods: ["stir-fry"],
    keyIngredients: ["squid", "chili", "garlic"],
    flavorTags: ["spicy", "savory"],
    dishForm: "dry-stir-fry",
    objectPosition: "68% 50%",
  },
  {
    id: "hero-steamed-crab-01",
    src: "/images/recipe-library/hero/steamed-crab.webp",
    dishNames: ["清蒸螃蟹", "Steamed Crab"],
    aliases: ["清蒸大闸蟹", "蒸螃蟹"],
    primaryCategory: "crab",
    ingredientForms: ["whole", "shellfish"],
    cookingMethods: ["steam"],
    keyIngredients: ["crab", "ginger"],
    flavorTags: ["light", "savory"],
    dishForm: "steamed-seafood",
    objectPosition: "68% 50%",
  },
  ...[
    ["chicken", "hero-fallback-chicken"],
    ["duck", "hero-fallback-duck"],
    ["pork", "hero-fallback-pork"],
    ["beef", "hero-fallback-beef"],
    ["fish", "hero-fallback-fish"],
    ["seafood", "hero-fallback-seafood"],
    ["other", "hero-fallback-other"],
  ].map(([primaryCategory, id]) => ({
    id,
    src: `/images/recipe-library/hero/fallback/${primaryCategory}.webp`,
    dishNames: [],
    aliases: [],
    primaryCategory,
    ingredientForms: [],
    cookingMethods: [],
    keyIngredients: [],
    flavorTags: [],
    dishForm: "category-fallback",
    objectPosition: "68% 50%",
    isCategoryFallback: true,
  })) as HeroVisualAsset[],
];
