import type { RecipeVisualAsset } from "@/types/recipeVisual";
import { productionRecipeVisualAssets } from "@/lib/recipe-visual/productionManifest";

export const recipeVisualManifest: RecipeVisualAsset[] = [
  {
    id: "protein-chicken-diced",
    src: "/images/recipe-library/cutouts/proteins/chicken-thigh-cutout-alt.png",
    presentation: "isolated",
    type: "protein",
    category: "chicken",
    tags: ["chicken", "chicken-thigh", "diced-chicken", "鸡", "鸡腿肉", "鸡丁"],
    compatibleActions: ["cutting", "marinating", "stir-frying"],
    aspectRatio: "4:3",
    visualWeight: 0.92,
  },
  {
    id: "protein-duck-sliced",
    src: "/images/recipe-library/proteins/duck/duck-slices-01.webp",
    type: "protein",
    category: "duck",
    tags: ["duck", "duck-slices", "鸭", "鸭肉"],
    compatibleActions: ["cutting", "braising", "roasting"],
    aspectRatio: "4:3",
    visualWeight: 0.9,
  },
  {
    id: "protein-pork-belly",
    src: "/images/recipe-library/proteins/pork/pork-belly-slices-01.webp",
    type: "protein",
    category: "pork",
    tags: ["pork", "pork-belly", "pork-slices", "猪", "猪肉", "五花肉"],
    compatibleActions: ["cutting", "stir-frying", "braising"],
    aspectRatio: "4:3",
    visualWeight: 0.92,
  },
  {
    id: "protein-beef-cubes",
    src: "/images/recipe-library/proteins/beef/beef-cubes-01.webp",
    type: "protein",
    category: "beef",
    tags: ["beef", "beef-cubes", "beef-brisket", "牛", "牛肉", "牛腩"],
    compatibleActions: ["cutting", "blanching", "simmering"],
    aspectRatio: "4:3",
    visualWeight: 0.93,
  },
  {
    id: "protein-fish-fillets",
    src: "/images/recipe-library/proteins/fish/fish-fillets-01.webp",
    type: "protein",
    category: "fish",
    tags: ["fish", "fresh-fish", "fish-fillets", "鱼", "鲜鱼", "鱼片"],
    compatibleActions: ["preparing", "steaming", "frying"],
    aspectRatio: "4:3",
    visualWeight: 0.9,
  },
  {
    id: "protein-seafood-shrimp",
    src: "/images/recipe-library/proteins/seafood/shrimp-shellfish-01.webp",
    type: "protein",
    category: "shrimp",
    tags: ["seafood", "shrimp", "shellfish", "海鲜", "虾", "鲜虾"],
    compatibleActions: ["preparing", "steaming", "stir-frying"],
    aspectRatio: "4:3",
    visualWeight: 0.91,
  },
  {
    id: "ingredient-scallion-ginger-garlic",
    src: "/images/recipe-library/ingredients/aromatics/scallion-ginger-garlic-01.webp",
    type: "ingredient",
    category: "aromatics",
    tags: ["scallion-ginger-garlic", "aromatics", "葱", "姜", "蒜", "蒜蓉"],
    compatibleActions: ["preparing", "frying-aromatics"],
    aspectRatio: "4:3",
    visualWeight: 0.78,
  },
  {
    id: "ingredient-dried-chili-peppercorn",
    src: "/images/recipe-library/cutouts/ingredients/kungpao-garnish-cutout.png",
    presentation: "isolated",
    type: "ingredient",
    category: "chili-pepper",
    tags: ["dried-chili-peppercorn", "chili-pepper", "干辣椒", "辣椒", "花椒"],
    compatibleActions: ["preparing", "frying-aromatics", "stir-frying"],
    aspectRatio: "4:3",
    visualWeight: 0.86,
  },
  {
    id: "ingredient-fresh-chili",
    src: "/images/recipe-library/ingredients/chili-pepper/fresh-chili-01.webp",
    type: "ingredient",
    category: "chili-pepper",
    tags: ["fresh-chili", "green-chili", "red-chili", "鲜辣椒", "青椒", "红椒"],
    compatibleActions: ["cutting", "stir-frying"],
    aspectRatio: "4:3",
    visualWeight: 0.76,
  },
  {
    id: "ingredient-onion-pepper",
    src: "/images/recipe-library/ingredients/vegetables/onion-pepper-01.webp",
    type: "ingredient",
    category: "vegetables",
    tags: ["onion-pepper", "vegetables", "洋葱", "彩椒", "胡萝卜", "土豆"],
    compatibleActions: ["cutting", "stir-frying", "simmering"],
    aspectRatio: "4:3",
    visualWeight: 0.78,
  },
  {
    id: "ingredient-mushroom-vegetables",
    src: "/images/recipe-library/ingredients/mushrooms/mushroom-vegetables-01.webp",
    type: "ingredient",
    category: "mushrooms",
    tags: ["mushroom-vegetables", "mushroom", "greens", "香菇", "蘑菇", "青菜"],
    compatibleActions: ["preparing", "stir-frying", "simmering"],
    aspectRatio: "4:3",
    visualWeight: 0.74,
  },
  {
    id: "ingredient-peanuts-nuts",
    src: "/images/recipe-library/ingredients/nuts/peanuts-nuts-01.webp",
    type: "ingredient",
    category: "nuts",
    tags: ["peanuts-nuts", "peanuts", "nuts", "花生", "坚果", "芝麻"],
    compatibleActions: ["preparing", "stir-frying", "plating"],
    aspectRatio: "4:3",
    visualWeight: 0.84,
  },
  {
    id: "seasoning-soy-wine",
    src: "/images/recipe-library/seasonings/soy-sauce/light-dark-soy-wine-01.webp",
    type: "seasoning",
    category: "soy-sauce",
    tags: [
      "light-dark-soy-wine",
      "soy-sauce",
      "cooking-wine",
      "生抽",
      "老抽",
      "酱油",
      "蒸鱼豉油",
      "料酒",
    ],
    compatibleActions: ["marinating", "mixing-sauce", "braising"],
    aspectRatio: "4:3",
    visualWeight: 0.82,
  },
  {
    id: "seasoning-vinegar-sugar",
    src: "/images/recipe-library/seasonings/vinegar-sugar/vinegar-sugar-salt-01.webp",
    type: "seasoning",
    category: "vinegar-sugar",
    tags: ["vinegar-sugar-salt", "vinegar", "sugar", "醋", "糖", "盐"],
    compatibleActions: ["mixing-sauce", "seasoning"],
    aspectRatio: "4:3",
    visualWeight: 0.76,
  },
  {
    id: "seasoning-starch-water",
    src: "/images/recipe-library/seasonings/starch/starch-water-01.webp",
    type: "seasoning",
    category: "starch",
    tags: ["starch-water", "starch", "slurry", "淀粉", "水淀粉", "清水"],
    compatibleActions: ["marinating", "mixing-sauce", "thickening"],
    aspectRatio: "4:3",
    visualWeight: 0.7,
  },
  {
    id: "seasoning-kung-pao-sauce",
    src: "/images/recipe-library/seasonings/mixed-sauces/kung-pao-sauce-01.webp",
    type: "seasoning",
    category: "mixed-sauces",
    tags: ["kung-pao-sauce", "mixed-sauces", "宫保汁", "碗汁", "调味汁"],
    compatibleActions: ["mixing-sauce", "stir-frying"],
    aspectRatio: "4:3",
    visualWeight: 0.88,
  },
  {
    id: "step-cutting-protein",
    src: "/images/recipe-library/steps/cutting/cutting-protein-01.webp",
    type: "step",
    category: "cutting",
    tags: ["cutting", "cutting-protein", "切", "切丁", "改刀"],
    compatibleActions: ["cutting"],
    aspectRatio: "1:1",
    visualWeight: 0.8,
  },
  {
    id: "step-marinating-chicken",
    src: "/images/recipe-library/steps/marinating/marinating-chicken-01.webp",
    type: "step",
    category: "marinating",
    tags: ["marinating", "marinating-chicken", "腌制", "抓匀", "上浆"],
    compatibleActions: ["marinating"],
    aspectRatio: "1:1",
    visualWeight: 0.88,
  },
  {
    id: "step-preparing-seafood",
    src: "/images/recipe-library/steps/preparing/preparing-seafood-01.webp",
    type: "step",
    category: "preparing",
    tags: ["preparing", "preparing-seafood", "处理", "开背", "去虾线", "鱼身"],
    compatibleActions: ["preparing", "steaming"],
    aspectRatio: "1:1",
    visualWeight: 0.78,
  },
  {
    id: "step-frying-aromatics",
    src: "/images/recipe-library/steps/frying-aromatics/frying-aromatics-01.webp",
    type: "step",
    category: "frying-aromatics",
    tags: ["frying-aromatics", "爆香", "炒香", "激香", "花椒", "辣椒"],
    compatibleActions: ["frying-aromatics"],
    aspectRatio: "1:1",
    visualWeight: 0.9,
  },
  {
    id: "step-stir-frying-chicken",
    src: "/images/recipe-library/steps/stir-frying/stir-frying-chicken-01.webp",
    type: "step",
    category: "stir-frying",
    tags: ["stir-frying", "stir-frying-chicken", "翻炒", "合炒", "鸡丁"],
    compatibleActions: ["stir-frying"],
    aspectRatio: "1:1",
    visualWeight: 0.92,
  },
  {
    id: "step-simmering-beef",
    src: "/images/recipe-library/steps/simmering/simmering-beef-01.webp",
    type: "step",
    category: "simmering",
    tags: ["simmering", "simmering-beef", "炖煮", "慢炖", "焖", "牛肉"],
    compatibleActions: ["simmering", "braising"],
    aspectRatio: "1:1",
    visualWeight: 0.9,
  },
  {
    id: "step-mixing-sauce",
    src: "/images/recipe-library/steps/mixing-sauce/mixing-sauce-01.webp",
    type: "step",
    category: "mixing-sauce",
    tags: ["mixing-sauce", "调汁", "碗汁", "调味汁", "搅匀"],
    compatibleActions: ["mixing-sauce"],
    aspectRatio: "1:1",
    visualWeight: 0.84,
  },
  {
    id: "step-plating-dish",
    src: "/images/recipe-library/steps/plating/plating-dish-01.webp",
    type: "step",
    category: "plating",
    tags: ["plating", "plating-dish", "装盘", "出锅", "盛出", "收汁"],
    compatibleActions: ["plating", "thickening"],
    aspectRatio: "1:1",
    visualWeight: 0.86,
  },
  ...productionRecipeVisualAssets,
];
